### ISSUE TITLE
Отрефакторить пагинацию

### ISSUE THREAD

**Issue by astynax** [Hexlet/hexlet-friends#112]
Сейчас в коде, который отвечает за пагинацию, всё очень хрупко. Есть и откровенно странные штуки вроде константы, объявляемой [посреди тела функции](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/contributors/views/mixins.py#L24) - ну не делают так! Ещё напрягают магические числа вроде [8](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/contributors/views/mixins.py#L21)/[3](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/contributors/views/mixins.py#L28) и `4`/`7` [там](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/templates/components/pagination.html#L12) и [здесь](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/templates/components/pagination.html#L25).

И вот [эта функция](https://github.com/Hexlet/hexlet-friends/blob/085406fbfa5853ffbd09f5b54788544cacbb5ecb/contributors/views/mixins.py#L12) вроде и обособлена, но на деле глубоко завязана на двукратно вложенный объект в роли аргумента. Это сильно усложняет тестирование. А тестировать надо бы! Особенно после отлова бага #111.

Предлагаю переделать функцию так, чтобы она возвращала только `paginator` а возвращала объект `slice`. Такое тестировать уже сильно проще: пагинатор легко замокать, а слайсы легко сравнивать. `8` и `3` нужно выразить либо одно через другое, либо через отдельный параметр функции, который передавать из константы в классе. Точно так же нужно передавать и `VISIBLE_AT_BOUNDARY` - чтобы класс, к которому примешивается пагинация, мог ею управлять. И шаблон нужно так изменить, чтобы никакие `4` и `7`  в нём не фигурировали, а брались из класса же (или вычислялись бы на основе его полей).

**Comment by astynax** [comment]
@antlu возьмешь?

**Comment by antlu** [comment]
Возьму.
