### ISSUE TITLE
CSV со списком публичных реп

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#142]
Привет, ребятки, можете подготовить csv файлик со список публичных реп?
форм `organization, repo_name, url`

**Comment by antlu** [comment]
Привет. У меня нет доступа к Хероку, но вот код для `./manage.py shell`:

```py
import csv
from contributors.models import Repository

repos = Repository.objects.select_related('organization').values_list('organization__name', 'name', 'html_url')

with open('repos.csv', 'w', newline='') as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(['organization', 'repo_name', 'url'])
    csv_writer.writerows(repos)
```

Я не знаю, какие репозитории добавлены в базу на Хероку; там могут быть и приватные.
Если нужны только отображаемые на сайте (а это не все публичные, потому что некоторые были скрыты), то надо добавить `.filter(is_visible=True)` перед `.values_list`.

Может, @corsicanec82 сможет помочь.

**Comment by corsicanec82** [comment]
@antlu спасибо за скрипт.
Воспользовался ним.
Кстати @fey у нас же есть вход в админку hexlet-friends, там тоже есть список организаций, реп и т.д. Но правда нет выгрузки в csv )
