### ISSUE TITLE
Не работает обновление активности

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#143]
Сейчас на главной отображается последний ПР за 2 недели назад, активность за декабрь отсутствует.
В ишшусах отображаются старые закрытые ишшусы, новых нет, пример такого ишшуса
https://github.com/Hexlet/hexlet-sicp/issues/1119
![image](https://user-images.githubusercontent.com/697178/145016170-59db7b19-cc97-409c-bcaf-ec2549c9ce8b.png)

**Comment by antlu** [comment]
Исправилось. Наверно, Станислав заходом на Хероку запустил процесс `clock`.
