### ISSUE TITLE
Добавить страницу пуллреквестов,ишшусов контрибьютера

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#147]
## Предлагаемая задача
Добавить страницы для просмотра пулл реквестов (с фильтрацией и сортировкой) и ишшусов (тоже фильтры и сортировка

https://friends.hexlet.io/contributors/fey/pullrequests
https://friends.hexlet.io/contributors/fey/issues

Бывает необходимо для сбора статистики\просмотра активности по юзеру

**Comment by EvilMadSquirrel** [comment]
Для ишшусов уже есть моделька с заголовком, создавать такую же для пулл реквеста? Вроде логично, если нужно их в список выводить.

**Comment by antlu** [comment]
Для Issues и PRs есть модель Contribution.
https://github.com/Hexlet/hexlet-friends/blob/94274c07df425ccc88d05090c670b8cb973bdb1d/contributors/models/contribution.py#L41
Различить можно по полю type.

**Comment by EvilMadSquirrel** [comment]
Другой вопрос: где в шаблоне расположить ссылки на эти страницы? Попробовал рядом с бейджиком гитхаба - кривовато получается :(

**Comment by antlu** [comment]
Можно сделать вкладки рядом с All-time contributions. Как блок с топ 10 на главной странице.

**Comment by EvilMadSquirrel** [comment]
> Можно сделать вкладки рядом с All-time contributions. Как блок с топ 10 на главной странице.

а тогда не получатся отдельные страницы с переходом по адресам (это будет дополнительными параметрами на текущей странице):
![image](https://user-images.githubusercontent.com/36692278/163148145-0248c07e-27d1-4235-945b-d244b4d1ad55.png)

**Comment by fey** [comment]
done
