### ISSUE TITLE
Завести OG теги (хотя бы на главную)

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#150]

**Comment by VasiliyBogdanov** [comment]
Взял. Вопрос: какую картинку/картинки мы куда хотим?(и где их взять?). Я предварительно добавил лого Хекслета [Лого](https://drive.google.com/file/d/1eaxDjzFcuE5wSRPxjqDmcfHOxNZf-zl4/view?usp=sharing) в расширении 1200:630 в base.html, конкретные ссылки сделаю через блоки.

**Comment by fey** [comment]
https://github.com/Hexlet/assets можно из ассетов взять, свг например)

**Comment by zhabinka** [comment]
@VasiliyBogdanov как продвигается задача? Нужна ли помощь?

**Comment by VasiliyBogdanov** [comment]
@zhabinka Извиняюсь, что долго, отправил коммит #186
