### ISSUE TITLE
Добавить в информацию о ПРах больше конкретики

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#163]
Пример - смотрю ПРы контриьютера, у него есть ПРЫ, которые не смержены (просто закрыты),
И непонятно смержены ли ПРы или нет. Просто статус Closed
Пример двух профилей
https://friends.hexlet.io/contributors/fey/pullrequests/
https://friends.hexlet.io/contributors/saymon-says/pullrequests/

ПР принят https://github.com/Hexlet/hexlet-correction/pull/93
ПР закрыт (не принят) https://github.com/Hexlet/hexlet-correction/pull/99

**Comment by antlu** [comment]
For reference: https://docs.github.com/en/rest/pulls/pulls#check-if-a-pull-request-has-been-merged
