### ISSUE TITLE
Improve the UX on the issues page

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#166]
Instead of grouping by projects and drop-down lists, make a table with filtering.
Make the tags of the repository itself, by language, by tags in issues
Link to https://friends.hexlet.io/issues

In this way you can immediately find the hash associated with a certain technology or a tag like "goodfirstissues". Some of the technologies (like bootstrap, js, etc.) are shared between several projects. (actually as a solution to use tags within the repo to indicate what is used in the project so that it is easier for newbies to find new tasks)

**Comment by zhabinka** [comment]
@fey всё, теги реализованы. Посмотри, плиз, что из предложенного тобой сейчас актуально, и можно ещё делать.

**Comment by devdenh** [comment]
беру в работу

**Comment by devdenh** [comment]
освободил

**Comment by ya-pekatoros** [comment]
Всем привет. Возьму задачу. Постараюсь оперативно.

**Comment by ssssank** [comment]
Набросали примерный внешний вид страницы:
![image](https://user-images.githubusercontent.com/17835285/229126681-81b91584-0694-454f-aa07-a9599b18b4ba.png)
![image](https://user-images.githubusercontent.com/17835285/229127769-f05fed7f-b6f3-4572-b310-bccdd5c63321.png)

В первую очередь убрать группировку по проектам и вывод ссылок обычным списком, а сделать таблицу, как на странице с пул-реквестами, необходимые столбцы у таблицы: 
  - Название
  - Репозиторий
  - Автор
  - Дата создания
  - Статус

Следующий шаг: разобраться в том, как получать нужные ишьюсы по лейблам, какое API гитхаба и как дергать, чтобы получить нужное. Для примера, можно сделать простой фильтр (radio btn) "Good first issue", чтобы выводить список из простых задачек. 

И последним шагом добавить фильтры по группам лейблов. Скорее всего, группы будут такие:
  - Type
  - Priority
  - Technology
  - Difficulty
  - Scope

**Comment by fey** [comment]
Как это сделано на гитхабе - https://github.com/orgs/hexlet-rus/projects/2/views/2

![image](https://user-images.githubusercontent.com/697178/230426056-4472d860-5333-4f5e-8429-f0f441659014.png)

**Comment by ya-pekatoros** [comment]
https://github.com/Hexlet/hexlet-friends/pull/268

Предлагаю посмотреть эти вот мои наработки. Там есть баг, который я не смог починить. 

Давайте объединим усилия и доведем до ума)

**Comment by SvetlanaAkaemova** [comment]
Беру задачу себе)

**Comment by ssssank** [comment]
В #282 идёт работа по добавлению фильтра по статусу, как там будет готово, останется только сделать фильтр по лейблам и будет более-менее юзабельно

**Comment by SvetlanaAkaemova** [comment]
У меня сейчас фильтр по good first issue, хотела ещё сделать фильтр по дате (не поняла, надо ли, но хотела). И по остальным у меня мультичойс. Подскажите, какой конкретно фильтр мне нужно тогда добавить, чтоб лишнее не делать?

**Comment by ssssank** [comment]
Там добавляют фильтр по статусу открыт/закрыт, всё остальное при желании можете делать вы :)

**Comment by SvetlanaAkaemova** [comment]
Вопрос. Сейчас вот колдую с лейблами. У меня как сейчас как на странице с репозиториями фильтруется по лейблам. Я делаю кнопку для good first issues. Есть ли смысл для нее, если этот лейбл тоже должен быть в шапке со всеми остальными? 
И по остальным столбцам сделать как на странице репозиториев? Т.е. просто нажатием на столбец будет фильтроваться. Или же сделать отдельно окошки? Группы лейблов Type, Priority и т д. актуальны?

**Comment by ssssank** [comment]
Если есть какой-то более-менее рабочий вариант, то уже стоить открыть ПР (можно в драфте) и задеплоить, чтобы мы могли посмотреть, как оно выглядит. Так будет проще отвечать на вопросы

Отдельная кнопка для good first issues имеет смысл, так как часто приходят новички и им здорово быстро увидеть простые ишьюсы

Группы лейблов актуальны

А вот про фильтрацию в столбцах не очень понятно

**Comment by SvetlanaAkaemova** [comment]
Фильтрация в столбцах как на странице с репозиториями. Т.е  каждый столбец можно 
упорядочить.
Столбцы как указано в обсуждении:
Название проблемы
Репозиторий
Автор
Дата создания
Статус

**Comment by ssssank** [comment]
Таблица же уже есть: https://friends.hexlet.io/issues
Да, в неё сломана сортировка по клику на заголовок, если вы это имели в виду, то можно поправить

**Comment by SvetlanaAkaemova** [comment]
Отправила ночью пуллреквест. Если какие фильтры не нужны, напишите пожалуйста, я исправлю. 
Добавила галку для good_first_issue,
Группы лейблов- пока просто есть фильтр, но без самих групп.
Плюс есть два фильтра - по названию проблемы и названию репозитория.
