### ISSUE TITLE
Get all user registration activity

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#174]

**Comment by acidmaksim** [comment]
Нужно чтобы вся активность пользователя с GitHub подтягивалась к нему на страницу при регистрации или привязке аккаунта к hexlet-friends. 
Активность:
- Pull request;
- Коммиты;
- Issues;
- и тд.

**Comment by neihaoo** [comment]
Здравствуйте, хочу попробовать взять данную задачу в работу.

**Comment by zhabinka** [comment]
Отлично!

**Comment by neihaoo** [comment]
@zhabinka возник вопрос по задаче. Вопрос связан с тем что у репозитория владелец может быть как пользователь так и организация, сейчас я просто добавил поле `owner` для модели `Repository` и связываю его с  пользователем если тип владельца пользователь, а не организация. А вообще я думаю что можно воспользоваться [Generic Relations](https://docs.djangoproject.com/en/4.1/ref/contrib/contenttypes/#generic-relations), чтобы связать владельца репозитория либо с пользователем либо с организацией. Но тогда там надо рефакторить код в других местах где он завязан на текущей реализации и впринципе это можно оформить и как отдельную задачу, либо сделать в рамках этой отдельным коммитом просто. Как лучше поступуть?

**Comment by neihaoo** [comment]
Пошел по простому пути пока.

**Comment by acidmaksim** [comment]
@neihaoo как дела?

**Comment by neihaoo** [comment]
@acidmaksim нормально,  PR отправил, жду проверки.
