### ISSUE TITLE
Make a Leaderboard (can be inspired by codebattle)

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#178]
Make a Leaderboard. A good example of a Leaderboard is at:
- [Codebattle](https://codebattle.hexlet.io/users)
- [Codewars](https://www.codewars.com/users/leaderboard)

Add more examples in the comments. 

<img width="408" alt="Снимок экрана 2022-07-26 в 3 42 39 PM" src="https://user-images.githubusercontent.com/77053797/181008428-648eee74-06ab-4fb3-994f-801d66015906.png">
<img width="1207" alt="Снимок экрана 2022-07-26 в 3 42 52 PM" src="https://user-images.githubusercontent.com/77053797/181008464-064ab3a8-6214-4478-b739-edc978553881.png">
<img width="1438" alt="Снимок экрана 2022-07-26 в 3 43 39 PM" src="https://user-images.githubusercontent.com/77053797/181008614-f0bcba0b-6746-45d8-87a0-8cad5b022405.png">

**Comment by LikerK** [comment]
Беру задачку)

**Comment by zhabinka** [comment]
@LikerK, привет! Как успехи?

**Comment by LikerK** [comment]
@zhabinka Привет! Только сейчас приступаю к задаче, до этого не смог :с

**Comment by LikerK** [comment]
@acidmaksim Привет! Пару уточнений:

**Comment by LikerK** [comment]
@acidmaksim Привет! Пару уточнений:
На hexlet-friends есть [leaderboard](https://friends.hexlet.io/) из топ 10 контрибьюторов, так же есть и [статистика](https://friends.hexlet.io/contributors/) всех пользователей за все время и за месяц, где можно сортировать по категориям, точно так же сделано на code battle.
Можешь пожалуйста подсказать, что еще можно добавить?

**Comment by acidmaksim** [comment]
@LikerK получается сделать?

**Comment by zhabinka** [comment]
Как минимум нужно добавить ТОП 10 за неделю и починить кнопку "За прошедший месяц" (она сейчас не работает).

**Comment by LilDrugHill** [comment]
Кнопкой занимаются?

> Как минимум нужно добавить ТОП 10 за неделю и починить кнопку "За прошедший месяц" (она сейчас не работает).
