### ISSUE TITLE
Add to the admin panel the ability to exclude users from the sample

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#181]

**Comment by ajib6ept** [comment]
Cейчас в админки есть возможность установить пользователю опцию отслеживать или/и отображать на сайте, подскажите пожалуйста, в рамках данного issue, что нужно сделать?

**Comment by acidmaksim** [comment]
Имеется ввиду, что можно исключать пользователей из какого либо списка. Но только у админов

**Comment by zhabinka** [comment]
Хорошо бы сделать группы пользователей. Например, добавить новую сущность – Команды.

**Comment by acidmaksim** [comment]
@ajib6ept Ты делаешь эту задачу?

**Comment by ajib6ept** [comment]
Нет, задачу не делаю, только уточнил её.

**Comment by kvazar941** [comment]
Добрый день! Беру задачу в работу.

**Comment by acidmaksim** [comment]
@kvazar941 как успехи?

**Comment by kvazar941** [comment]
День добрый! Если я правильно понял задачу - нужно, чтобы в админке помимо категории 'Пользователи' была категория 'Группы' (или 'Команды', 'Подразделения' и т.д.). Тогда каждый пользователь сайта должен быть отнесен к какой - либо группе, либо входить в отдельную группу, например, 'Прочие'. И вот здесь нужна возможность удалять пользователей из групп? Попутно вопрос: сами пользователи должны каким либо образом взаимодействовать с этим инструментом группировки?

**Comment by acidmaksim** [comment]
@emp7yhead подскажи
