### ISSUE TITLE
Add the ability to see activity on your group of projects. For example, on Hexlet projects

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#183]
Make it possible to view activity on your group of projects.

- Number of PRs;
- Completed Issues;
- Comments;
- etc.

**Comment by Perceptor89** [comment]
Можете, пожалуйста, подробнее раскрыть задачу? Где происходит отображение, как должна происходить группировка...

**Comment by Dddarknight** [comment]
беру в работу

**Comment by acidmaksim** [comment]
@Dddarknight как успехи?

**Comment by Dddarknight** [comment]
@acidmaksim  https://github.com/Hexlet/hexlet-friends/pull/195
