### ISSUE TITLE
Добавить ачивки за первый PR, за количество строк кода, за 50 комитов и т.д.

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#184]
Нужно продумать в каких случаях давать пользователю награды. 
Например:
- За 1, 10, 30, 50, 100 принятые PR;
- За 1000, 5000, 10000 и тд строк кода;
- За 1, 10, 30, 50 и тд, выполненные Issues;
- За 10, 50, 100 и тд комментариев;
- И так далее

**Comment by acidmaksim** [comment]
You can draw yourself a simple achieves or take some icons, it is important that they have an open license.

**Comment by mnogom** [comment]
Коллеги, есть дилемма

Смысл в следующем. Я посмотрел, как устроены [ачивки на codebattle](https://github.com/hexlet-codebattle/codebattle/blob/master/services/app/lib/codebattle/user/achievements.ex). С `Clojure` я не знаком, но если я правильно понял, то там они рассчитываются при запросе исходя из статистики в момент запроса. То есть, по факту они не хранятся в БД. Поправьте, пожалуйста, если я ошибаюсь.

В нашей задаче вижу два варианта:
1. Поступить так же: берём данные, которые у нас уже есть в `context` html-шаблона из вьюхи -> мапим с условиями (например, коммитов > 50) -> выводим если `True`
* \+ Довольно просто реализовать, небольшое время на реализацию
* \- Невозможно собрать статистику (время получения, какое действие было тригером для получения и тп)
* \- Не знаю, как правильно сформулировать, но ачивки станут абстракцией шаблона, соответсвенно добавлять новые нужно будет через `template` / `templatetags`
2. Усложнить. Добавить отдельную сущность `Achievments`, связать её с `User` как `m2m`, и добавлять в контекст
* \- Сложнее, дольше делать
* \+ Можно обвязать статистикой

Интересно попробовать реализовать второй случай, но тогда есть пара концептульных проблем:
1. Нужен, видимо, планировщик, чтобы сгружать новые показатели, а это нагрузка на сервер.
2. Придумать. как описывать тригеры для получения ачивок, чтобы можно было их менеджерить через админ-панель

По какому пути стоит пойти?

**Comment by acidmaksim** [comment]
@zhabinka  поможешь, пожалуйста?

**Comment by mnogom** [comment]
Пока пошёл по первому пути
