### ISSUE TITLE
Отредактировать пользователя через админку

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#193]
Ребята, сделайте, плиз, меня tracked и visible на сайте. Логин – zhabinka.

**Comment by ashikov** [comment]
@sgmdlt можем помочь с этим?

**Comment by zhabinka** [comment]
@corsicanec82 у тебя, вроде, доступ в админку есть.

**Comment by acidmaksim** [comment]
@zhabinka issues актуален?

**Comment by fey** [comment]
done
