### ISSUE TITLE
Сделать страницу О проекте

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#194]
Стоит сделать страницу О проекте, рассказать, для чего он создан, какие возможности есть у сервиса. По аналогии с Hexlet SICP – https://sicp.hexlet.io/ru/pages/about

**Comment by pppershin** [comment]
Я возьму в работу

**Comment by ilnarkz** [comment]
Возьму в работу

**Comment by ilnarkz** [comment]
Я еще раз пробую)
