### ISSUE TITLE
Fix localization

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#203]
No translation in Russian

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/77053797/201938518-367b3a77-01af-4182-a751-eb403c2a217b.png">

**Comment by seregad544** [comment]
взял задачу

**Comment by AlexSubach** [comment]
В этой задаче, нужно переводить только это место? Или задача на перевод всех мест в проекте?)

**Comment by antlu** [comment]
Перевод указывается в одном месте и переиспользуется в остальных.
