### ISSUE TITLE
Выровнять таблицы на главной страницы

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#206]
## Ожидаемое поведение
Нужно выровнять таблицы, что бы они были на одном уровне
Эти таблицы находятся на главной https://friends.hexlet.io/

![image](https://user-images.githubusercontent.com/77053797/204544736-270e2074-e4ce-47e7-a07c-5049ecc1b5a7.png)

**Comment by Heymen22** [comment]
Взялся за выполнение.

**Comment by acidmaksim** [comment]
@Heymen22 эта задача занята за @tragoedie

**Comment by Heymen22** [comment]
@acidmaksim Понял. Думал свободна, раз никто не отписался в issue.

**Comment by acidmaksim** [comment]
@Heymen22 не могу тебя определить по нику. 
Напиши мне, пожалуйста, в студ слаке, если ты наш студент)
Что нибудь придумаем по другой задачке

**Comment by Heymen22** [comment]
@acidmaksim Я не студент, но в слаке хекслета я зарегестрирован как Умпелев Иван
