### ISSUE TITLE
Correct an error on the members page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#210]
## Ожидаемое поведение
The "Last month" button should show students for the month. 

## Текущее поведение
Now this button does not work, only the display for the week works. 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/77053797/206660320-7d6d1e47-eae2-435a-b526-493665c061b2.png">

**Comment by neihaoo** [comment]
@acidmaksim а есть ли смысл сейчас в этих кнопках вообще?
Может просто по аналогии с тем как сделано сейчас в навигации добавить еще пункт с переходом на страничку с участниками за неделю.
<img width="791" alt="Screenshot 2022-12-12 at 12 33 42" src="https://user-images.githubusercontent.com/30729586/207011394-43b84a96-57e1-43cd-ba9d-bf5caf6fe66b.png">

**Comment by yuriy-kormin** [comment]
Попробовал сделать. посмотрите пулл-реквест

**Comment by M1RRoN** [comment]
задача сделана?

**Comment by emp7yhead** [comment]
@M1RRoN да, задача выполнена
ref #231
