### ISSUE TITLE
Make it possible to hide your data on some projects

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#215]
## Предлагаемая задача
Make it possible to hide your data on some projects

**Comment by choolkov** [comment]
I took this task

**Comment by choolkov** [comment]
I am making it possible to hide repositories whose owner is a logged-in user, but there is still a question whether it is necessary to implement hiding of specific contributions, such as pull requests, issues, etc.?
And how would it be better, a separate view for settings (link) in contributor page or something like checkboxes in existing lists in the contributor page (pull requests and issues)?

**Comment by acidmaksim** [comment]
@emp7yhead помоги, пожалуйста

**Comment by fey** [comment]
@emp7yhead тут есть контекст, что нужно было сделать?)

**Comment by emp7yhead** [comment]
@fey без понятия)

**Comment by fey** [comment]
@acidmaksim подскажешь?)

**Comment by acidmaksim** [comment]
@fey привет) Насколько я помню, эта таска подразумевала под собой скрытие каких либо проектов из friends. Например, у человека есть какой-то проект публичный, но он его не хотел бы показывать во френдс.

**Comment by EmilMorua** [comment]
@fey Привет!

Правильно понимаю задачу?

На странице /about в разделе Возможности сервиса добавить возможность убирать репозитории из статистики и ссылку на форму для отправки админам. В форме юзернэйм и ссылка на репо

Если да, то беру задачу в работу

**Comment by fey** [comment]
@EmilMorua на страницу /about добавляем абзац  в стиле "Если вы хотите удалить какой-то репо из нашего сервиса - создайте issue на гитхаб по ссылке". По ссылке должна открываться шаблонная форма для ишшуса. 
Например как для фича реквеста - https://github.com/Hexlet/hexlet-friends/issues/new?assignees=&labels=&projects=&template=feature_request.md&title=

Т.е. нужно будет для этого добавить шаблон формы (посмотрите, как устроены шаблоны для багрепорта и фича реквеста). По полям формы - можно пофантазировать, думаю должно быть поле со ссылкой на сервис. Плюс например какой-то текст, типа подтверждающий, что вы администратор репозиория

**Comment by EmilMorua** [comment]
@fey Я пока начал сегодня делать проект у меня было такое виденье:
Пользователь переходит по ссылки формы на /about, у него проверяется аутентификация и если ее нет, то идет перенаправление на аутентификацию.
Если есть, то появляется форма со списком репозиториев пользователя с чекбоксами. Далее идет выбор репозиториев, которые нужно скрыть и отправка.

Как я понял, в модели Repository есть атрибут is_visible отвечающий за отображение репозитория. Запрос через форму будет менять его у выбранных репо.
Или я не так понял работу проекта?


Что будет со списком ишью на гитхабе если туда будут попадать азадчки на скрытие?)

**Comment by fey** [comment]
@EmilMorua дело в том, что щас в админке есть ручное удаление репозитория. Дело в том, что это не сильно приоритетная вещь и мб ей будут пользоваться никогда. Т.е. в таком случае лучше не писать вообще код или написать его максимально мало. Т.е. такая MVP версия. 
Если потребуется удалять репы много и постоянно - сделаем настройку пользователю.

**Comment by EmilMorua** [comment]
@fey Понял. Тогда пара вопросов:
1. На какой сервис должна быть ссылка в ишьюсе?
2. Что за текст подтверждающий владение репозиторием? Разве это не по профилю пользователя должно проверяться?

**Comment by EmilMorua** [comment]
@fey Добавил:
- текст с ссылкой на /about
- перевод текста
- шаблон для задачи на GitHub

**Comment by EmilMorua** [comment]
@fey Я что то не так сделал? В форке тесты проходят, ПР отправил. Или в очереди пока?

**Comment by fey** [comment]
@EmilMorua я вам в ПР комментарий оставил. был смержен другой ПР и в нем изменился файл с локалями. Поэтому в вашем репозитории нужно разрешить конфликт.

**Comment by EmilMorua** [comment]
@fey Добрый день! Переделал ПР. Конфликтов нет больше
