### ISSUE TITLE
Add filters by category in issues

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#216]
## Предлагаемая задача
Now there are no tags on the [page](https://friends.hexlet.io/issues) and it is inconvenient to search for tasks. 
We need to add tags by category:
technologies, bug or feature, discussions

**Comment by devdenh** [comment]
https://github.com/Hexlet/hexlet-friends/issues/166
вроде похожий, разве нет ?

**Comment by seeu359** [comment]
Беру в работу)

**Comment by acidmaksim** [comment]
@seeu359 получается решить задачу?

**Comment by ya-pekatoros** [comment]
Всем привет. Возьму задачу. Постараюсь оперативно.

**Comment by ya-pekatoros** [comment]
https://github.com/Hexlet/hexlet-friends/pull/268

Предлагаю обсудить. В PR описана текущая проблема и есть демонстрация.

**Comment by emp7yhead** [comment]
closed #268
