### ISSUE TITLE
Make filtration by statuses on the PR page.

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#217]
## Предлагаемая задача
Make filtration by tags on the [PR page](https://friends.hexlet.io/pull_requests?page=4). 
Now it is implemented very inconveniently and when searching for closed PRs, the sample does not get what you need

**Comment by bogdan-ho** [comment]
Беру в работу

**Comment by odhako** [comment]
Я бы взял в работу. Что есть теги? статусы? может лейблы?

**Comment by odhako** [comment]
Взял в работу.

**Comment by EmilMorua** [comment]
@acidmaksim Здравствуйте! А что за теги?

@odhako Как с задачей дела?

**Comment by acidmaksim** [comment]
Насколько я помню, подразумевалась фильтрация по статусам, так как сейчас там в столбце статусы идет все подряд. 
@emp7yhead может вспомнишь)

**Comment by bikowskiy** [comment]
Добрый день! Актуально? Могу взять в работу?

**Comment by fey** [comment]
@bikowskiy Привет, да эта задача актуальна. Сейчас нет фильтров на странице, только по названию https://friends.hexlet.io/pull_requests

**Comment by ratushnyivm** [comment]
@fey привет, посмотри пожалуйста #366

**Comment by al-ov73** [comment]
Задача уже не актуальная? Может добавить еще какие-то фильтры?

**Comment by fey** [comment]
Давайте фильтр добавим по репозиториям и по дате (создан от до),

**Comment by al-ov73** [comment]
ок, беру в работу
