### ISSUE TITLE
Add landing on project

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#218]
## Предлагаемая задача
Необходимо сделать лендинг для проекта, о том, что это за проект, какие возможности предоставляет. 
Первая страница должна содержать кнопку с призывом зарегистрироваться. также как и последняя. 
Итогового дизайна нет, есть пример для друогого проекта - https://www.figma.com/file/vgcW4DP894ULN2CSAE7jbO/RunIT-(Copy)?type=design&node-id=0-1&t=I5KsiSxbHGeyRb8a-0
Используем только Bootstrap, без кастома
Всякие примеры компонентов можно посмотреть в сайтах с примерами, вот пример с тайлвиндом. https://tailwindui.com/components/#product-application-ui

**Comment by vladikKir** [comment]
Беру в работу

**Comment by MarfaNikitina** [comment]
Попробую взять в работу. Подскажите что есть the banding page?

**Comment by MarfaNikitina** [comment]
Освободила задачу, не успеваю пока. Если кто хочет-берите

**Comment by fey** [comment]
@ssssank закинь плз сюда дизайн/референсы

**Comment by Cristikijian** [comment]
Я правильно понимаю, дизайн любой по ссылке взять? И каковы сроки исполнения?

**Comment by fey** [comment]
по дизайну мы с @ssssank званивались и накидывали примеры страниц. 
Суть в том, что по оисанию на лендинге должно быть понятно что это за проект, какие боли он решает. На первом экране кнопочка с регистрацией. Можно подглядеть лендинги на Хекслете например, отсюда брать дизайн блоки:
https://froala.com/design-blocks/#
https://tailwindui.com/

**Comment by fey** [comment]
По срокам - жестких нет. Просто если несколько человек будут делать.То первый пришлет ПР, того и тапки) (но конечно будет смотреть, что получилось)

**Comment by Cristikijian** [comment]
>  Суть в том, что по оисанию на лендинге должно быть понятно что это за проект, какие боли он решает. 

Описание тоже самостоятельно придумать?

**Comment by Cristikijian** [comment]
Я беру задачу

**Comment by fey** [comment]
Да, без проблем. Потом покорректируем)

**Comment by fey** [comment]
без реакта, жса по минимуму. Используем стандартные возможности Bootstrap, ибо все будет с бекенда.
Можно сперва просто HTML сделать нужный, а потом его можно нарезать на шаблонизаторе.

**Comment by Cristikijian** [comment]
По какому адресу будет лэндинг размещен? Нужен template под него, как я понимаю (если что, Phyton не знаю)?

**Comment by ssssank** [comment]
Да прям на главной скорее всего: https://friends.hexlet.io/

**Comment by Cristikijian** [comment]
Появилась пара вопросов. 
1)Дошла до топа участников. Нужно будет по таком уже принципу фильтровать, как сейчас?
2)Цвета. Сейчас попробовала взять оттенок из фавикона (индиго, который по дефолту в tailwind, в сочетании с фавиконом вызывает диссонанс). Это ок, или планируется какое-то другое лого? 
3) Авторизации сейчас вроде только через гитхаб, так и будет?

**Comment by Cristikijian** [comment]
> без реакта, жса по минимуму. Используем стандартные возможности Bootstrap, ибо все будет с бекенда. Можно сперва просто HTML сделать нужный, а потом его можно нарезать на шаблонизаторе.

Сейчас использую рекомендованный tailwind, без бутстрапа, нужно бутстрап вместо него? Немного запуталась.

**Comment by fey** [comment]
Ребята, тайлвинд не используем. В проекте используется Bootstrap.
Ну и поскольку это лендинг, то и реакта там нет. По сути это 2-3 страницы с описаннием проекта, с завлекаловом - что это за проект, какие штуки дает и тд.

**Comment by Cristikijian** [comment]
> Ребята, тайлвинд не используем. В проекте используется Bootstrap.
> Ну и поскольку это лендинг, то и реакта там нет. По сути это 2-3 страницы с описаннием проекта, с завлекаловом - что это за проект, какие штуки дает и тд.

Если не используем тэйлвинд, зачем тогда и в обсуждении, и в описании самой задачи его предлагается использовать? Я уже сделала верстку с его помощью.

**Comment by fey** [comment]
Это пример. Здесь не предлагается использовать сам тайлвинд, а как пример лендингов/верстки разных компонентов.
Например на Хекслете разработчики поглядывают в разные ui киты, в примеры на тайлвинде, но при это используют бутстрап.

**Comment by Cristikijian** [comment]
Задачу освобождаю, без внятного ТЗ качественная реализация не представляется мне возможной.

**Comment by fey** [comment]
@asenka0301 оставьте коммент в этом ищщусе, я назначу его на вас.
У нас нет дизайна, как такового, но нам бы хотя бы накидать основные блоки. В качестве вдохновения можно использовать Хекслет. 
Верстка вся на бутстрапе. Можно поискать какие-то готовые макеты-примеры, можно глянуть компоненты у тайлвинда. В этом ищщусе накидывали. 
Из основного, что прям должно быть

- hero блок с кнопкой-действием на первом экране с призывом регистрироваться.

**Comment by asenka0301** [comment]
Беру в работу
