### ISSUE TITLE
Reduce the appearance time of the tooltip on the achievement

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#225]
## Предлагаемая задача
We need to reduce the time of appearance of the tooltip on the achieves to 1 second

<img width="278" alt="image" src="https://user-images.githubusercontent.com/77053797/209827466-7649976d-b4e1-4ec3-84df-bdc1663268ef.png">

**Comment by Tragoedie** [comment]
Берусь за задание.в
