### ISSUE TITLE
Rename dropdown item

### ISSUE THREAD

**Issue by emp7yhead** [Hexlet/hexlet-friends#232]
Label for one of dropdown item in contributors menu is "For month", but you can select a period there. Recommend change label to "For period" 
<img width="187" alt="image" src="https://user-images.githubusercontent.com/20521260/213690123-f2394aa0-23c8-4451-9ee8-6caa855402f1.png">

**Comment by yuriy-kormin** [comment]
беру в работу

**Comment by Jainex17** [comment]
can i work on it?

**Comment by flamesjames** [comment]
Hey there @emp7yhead! Does this issue still need to be addressed? If so, I would be glad to help out with it.

**Comment by emp7yhead** [comment]
@flamesjames @Jainex17 sorry but @yuriy-kormin was the first to respond

**Comment by flamesjames** [comment]
@emp7yhead no worries at all! If you have any similar issues come up, or any that you think would be "good first issues", I'd be happy to help out any way I can

**Comment by yuriy-kormin** [comment]
Please reassign it to @DzmitrySha

**Comment by DzmitrySha** [comment]
Ready to fix this issue.
