### ISSUE TITLE
Add separation into PR and issues on the main page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#240]
**Проблема:**

Now the table shows PR and issues. This is not very convenient, because it is difficult to perceive. Need to split it into two tabs: PR and Issues

**Какие шаги нужно воспроизвести:**

1. Go to https://friends.hexlet.io/
2. Go down to "New PRs and issues

**Как это сейчас:**

<img width="677" alt="image" src="https://user-images.githubusercontent.com/77053797/216235687-4713a760-83d4-4db8-a997-ef0fdf5fa376.png">

**Как это должно работать:**

Similar to the Top 10
Add buttons: "for the past week", "for the past month"

Add tabs: "PR" and "Issues"

Translate these buttons
<img width="666" alt="image" src="https://user-images.githubusercontent.com/77053797/216235723-a182b712-4277-4780-a503-91bf3d01ed66.png">

**Comment by acidmaksim** [comment]
@Tragoedie

**Comment by Tragoedie** [comment]
Берусь за задание

**Comment by roaddust2** [comment]
Взял в работу

**Comment by emp7yhead** [comment]
closed #261
