### ISSUE TITLE
The hexlet-rus page does not open

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#241]
## Ожидаемое поведение
The Hexlet-Rus repository projects page should open. 
Example: https://friends.hexlet.io/organizations/hexlet-codebattle

Correct link on hexlet-rus: https://github.com/hexlet-rus

## Текущее поведение
1. On the Organization page hexlet-rus is duplicated. Remove duplication

2. There is a 500 error when opening hexlet-rus

![image](https://user-images.githubusercontent.com/77053797/216241553-bfce6b8f-88c7-4bcb-950d-efd51bfb806a.png)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/77053797/216241599-7ad53864-994d-4347-aee4-4c28c17ee400.png">

## Дейсвия по воспроизведению

1. Open https://friends.hexlet.io/organizations/
2. Click on hexlet-rus

**Comment by Tragoedie** [comment]
Берусь за задание

**Comment by fey** [comment]
Оказалось, что все проще - в бд были дубли.
