### ISSUE TITLE
404 ошибки

### ISSUE THREAD

**Issue by ajib6ept** [Hexlet/hexlet-friends#247]
## Текущее поведение

Есть не рабочие ссылки, которые возвращают 404 ошибку

## Дейсвия по воспроизведению

При переходе в раздел "[Пул-реквесты](https://friends.hexlet.io/pull_requests)" есть ссылки, например [#103 added routing](https://github.com/Hexlet/hexlet-editor/pull/107), которые возвращают 404 ошибку

**Comment by acidmaksim** [comment]
@ajib6ept сделай скриншот ошибки. 
Это скорее всего связано с тем, что репозиторий лежит в архиве и поэтому ты не можешь его увидеть

**Comment by EmilMorua** [comment]
Беру в работу!

**Comment by fey** [comment]
@EmilMorua по идее мы должны трекать, что репозиторий еще публичный.

**Comment by EmilMorua** [comment]
@fey что означает трекать?)

**Comment by fey** [comment]
@EmilMorua когда синхронизируем информацию с github, смотреть, что есть такой репозиторий. если он вдруг пропал - то как-то помечать его, что такого репозитория больше нет.
