### ISSUE TITLE
Add deployment instruction for Railway

### ISSUE THREAD

**Issue by emp7yhead** [Hexlet/hexlet-friends#249]
At this moment, the project has no instructions on how to deploy it.  This can cause problems for people who are joining an open-sourse for the first time. It would be a good idea to write deployment instruction for Railway.

**Comment by saurabh12571257** [comment]
Hey, wanted to contribute to deploy instructions for railway can I get the project if its free.

**Comment by emp7yhead** [comment]
@saurabh12571257 of course, feel free to contribute.

**Comment by emp7yhead** [comment]
@saurabh12571257 how work with issue is going?

**Comment by ssssank** [comment]
@emp7yhead думаю можно закрыть?

**Comment by emp7yhead** [comment]
Да-да, я чет проморгал
