### ISSUE TITLE
Fix Buttons on main page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-friends#250]
## Ожидаемое поведение
Clicking on the button "for the past week" should display the statistics for the past week. 

Clicking on the button "for the past month" should display statistics for the past month

## Текущее поведение

The "for the past week" and "for the past month" buttons work on the home page. Therefore, it is not clear for which period the statistics are displayed
![image](https://user-images.githubusercontent.com/77053797/217190521-421b98b2-7a15-4c19-902c-c1db84d9b150.png)

## Дейсвия по воспроизведению
1. Go to https://friends.hexlet.io/
2. Go to "Top 10 contributors"

**Comment by zhek111** [comment]
Беру
