### ISSUE TITLE
Gather information about users organizations to see users activities of the organization

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#257]
## Problem Description

Некоторая организация имеет пул активных пользователей, которые могут участвовать в опенсорсе. Эта организация попросила нас научиться агрегировать и выводить информацию об этих пользователях

## Proposed solution

В качестве решения мы будем собирать на hexlet-friends информацию о том, в каких организациях состоит пользователь, в том числе о скрытых организациях. 
Дальше добавляем фильтр на страницу контрибьютеров и учимся фильтровать юзеров по организации, в которую они входят. Ищем по названию организации. 

![image](https://user-images.githubusercontent.com/697178/226305392-537ad340-70ca-490a-a4c6-3079860abab8.png)

**Comment by fey** [comment]
@Un1que11 привет, как успехи?

**Comment by Un1que11** [comment]
@fey Пока тяжеловато, но делаю понемногу

**Comment by fey** [comment]
@Un1que11 смотри, наверняка задачу можно разделить по частям. Плюс ты можешь создать пулл реквест в Draft, чтобы мы могли видеть твой код и ребята могли помочь двигаться в нужном направлении.

**Comment by Un1que11** [comment]
@fey Я думал сейчас больше акцент на четвёртый проект сделать, чтобы опыта ещё накопиться, а потом вернуться к этому заданию

**Comment by fey** [comment]
а, оке

**Comment by ssssank** [comment]
@Un1que11 как успехи? вернёшься к этой задаче или её может забрать кто-нибудь другой?

**Comment by sidnnov** [comment]
Могу я забрать задачу?

**Comment by fey** [comment]
Да, конечно. Только учитывайте, что она может быть не самой простой. Не стесняйтесь ее декомпозировать.

**Comment by sidnnov** [comment]
Вопрос по поводу этой issue, я вроде бы сначала понял, а сейчас начал думать что не очень.. требуется реализовать совместный фильтр по именам и организациям, если я например введу в поиске Hexlet то участники должны быть отфильтрованы только по по одной организации? т.е. hexlet-basics уже не должен попасть?

**Comment by fey** [comment]
Давайте для простоты сделаем поиск по вхождению. Т.е. если пишем hexlet то будет выводиться `hexlet, hexlet-basics, hexlet-college`
