### ISSUE TITLE
Add check for unique organization name

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#263]
https://github.com/Hexlet/hexlet-friends/issues/241 - в БД были дублированы две организации.
Необходимо проверить и добавить валидацию, чтобы можно было создать только с уникальным названием организацию.

**Comment by NLastya** [comment]
Берусь за работу

**Comment by ssssank** [comment]
@NLastya получилось взяться за задачу?

**Comment by Labidahrom** [comment]
Берусь за задачу
