### ISSUE TITLE
Add achievements page

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#265]
Пользователи могут получать достижения, но нет инфы, какие есть.

Предложение сделать страницу со списком ачивок.
Вывести можно просто списоком, с пояснением, как их получить.
Дизайн будет чуть попозже.

Рефы:

https://steamcommunity.com/stats/227300/achievements
![image](https://user-images.githubusercontent.com/697178/230475197-f6b8a3bb-679d-423a-848d-8187e56dd054.png)
![image](https://user-images.githubusercontent.com/697178/230474577-0998a2e1-a061-4b22-bd11-ecc4eb594fc9.png)

**Comment by danokp** [comment]
Привет!
Если эта задача актуальна, то я бы попробовал реализовать.
1) Я же правильно понимаю, что, по сути, у нас есть следующие достижения:
1. Hexlet friend - одинаковая для всех
2. Pull requests
3. Commits
4. Issues
5. Comments
6. Additions and deletions
Достижения 2-6 имею разные уровни в зависимости от активности пользователя, а, значит, в описании награды надо указать, что нужно, чтобы перейти с одного уровня награды на другой.
Или есть еще какие-то более редкие награды?
2) Клик по любой из наград должен перенаправлять на страницу с их описанием?

**Comment by ssssank** [comment]
Кажется, это все ачивки, но можно уточнить у @fey 

Обычно подсказки делаются всплывашками при наведении на значок. Может быть можно и общую страницу сделать

**Comment by fey** [comment]
Привет, щас можно сделать пока страницу типа /achievements, где будет список ачивок. Без страниц отделных ачивок (их можно добавить позднее). 
Просто список того, что можно получить. И условие.
Потом постепенно можно добавлять новые страницы.

**Comment by fey** [comment]
Тут просто такая штука, что не хватает понимания, какие вообще ачивки есть, кто их получил и так далее.
