### ISSUE TITLE
Add filter to issues of user

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#266]
Добавить возможность фильтровать по состоянию - селект со значениями, по статусам - открытые, закрытые, все (пустой инпут)

![image](https://user-images.githubusercontent.com/697178/230477136-265630c2-3649-43bc-92a1-b7e9371f2682.png)

**Comment by Dzigr** [comment]
Беру в работу.

**Comment by ssssank** [comment]
@Dzigr как успехи? нужна ли помощь?

**Comment by Dzigr** [comment]
@ssssank Пока завал на работе, постараюсь составить вопросы (если возникнут) до конца следующей недели.

**Comment by Dzigr** [comment]
Closed with [#282](https://github.com/Hexlet/hexlet-friends/pull/282)

**Comment by fey** [comment]
так, стопэ) У нас же еще не учитываются статусы открыто-закрыто)

**Comment by serVmik** [comment]
Привет, задача актуальна?
Возьму в работу.
Как я понял, осталось добавить только чекбокс для фильтрации по статусу задачи "открыта"/"закрыта".

**Comment by fey** [comment]
Ага, надо https://friends.hexlet.io/issues/ ссылку на эту страницу переименовать.

**Comment by serVmik** [comment]
Взял в работу

**Comment by TarakanovAndrey** [comment]
А разве здесь впринципе не должны оставаться только открытые issues? А закрытые просто не должны появляться в списке

**Comment by fey** [comment]
Предположим мы хотим посмотреть ищщусы, которые открывались ранее, чтобы понять, как часто они закрываются.
