### ISSUE TITLE
Раздел "Участники" поле "Фильтрация по организациям" на английском языке, при русской локализации.

### ISSUE THREAD

**Issue by AavadaKedavra** [Hexlet/hexlet-friends#289]
## Ожидаемое поведение
При выборе локализации (RUS) все элементы интерфейса должны соответствовать выбору языка.

## Текущее поведение
Поле "Фильтрация по организациям" при выборе языка RUS - обозначено как "Filter by organization"
Баг воспроизводиться в таблице "за период" и в таблице "за все время"
![image](https://github.com/Hexlet/hexlet-friends/assets/126116401/af17be65-2de8-4fc5-a9c7-291837ddb39c)

## Возможные решения
Переименовать поле для русской локализации

## Дейсвия по воспроизведению
1.  Открыть https://friends.hexlet.io/contributors/for-month
2.  Открыть https://friends.hexlet.io/contributors/

## Информация о вашей системе
**Browsers:** Brave, Chrome
**System** Windows 10 pro

**Comment by Dzigr** [comment]
Исправлю
