### ISSUE TITLE
Не работает фильтр for the past month на странице contributors

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#293]
## Ожидаемое поведение
При нажатии на фильтр for the past month на странице contributors будет выведен список участников за месяц

## Текущее поведение
при нажатии на фильтр for the past month на странице contributors ничего не происходит

## Действия по воспроизведению

1. На странице https://friends.hexlet.io/ перейти в раздел "contributors", выбрать в выпадающем меню вариант for period
2. Нажать фильтр for the past month
3. Проверить изменение списка

## Информация о вашей системе

Win10, Chrome
Android 12

## Информация об установленных зависимостях

    pip freeze

**Comment by NikGor** [comment]
Привет! Беру в работу

**Comment by fey** [comment]
@Shvidunov проверьте, пофиксили ли

**Comment by Shvidunov** [comment]
Проверено, работает
