### ISSUE TITLE
Изменение цветовой индикации фильтров на странице open issues

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#294]
## Предлагаемая задача

на странице open issues все фильтры при первом переходе выглядят активными (синего цвета), хотя они не задействованы.
Если пошагово нажать на каждый - происходит фильтрация по лейблам, но при этом исчезают все нерешенные проблемы без лейблов. в итоге все активные фильтры выглядят также как и все неактивные.

![image](https://github.com/Hexlet/hexlet-friends/assets/121935818/06a123fe-d49f-44e0-82cb-e188279c3694)

![image](https://github.com/Hexlet/hexlet-friends/assets/121935818/0f439419-aaeb-484d-a02b-a8ca2427afc0)

## Решения задачи

отключить индикацию фильтров до их непосредственного использования (серые фильтры при открытии страницы), возможно добавить фильтр no labels

**Comment by NikGor** [comment]
кроме цветовой индикации не работает пагинация, переход на 2 страницу приводит к Not Found: The requested resource was not found on this server. Создадите отдельное issue на проблему?

**Comment by NikGor** [comment]
реализовал аналогичный фильтр по лейблам у себя в локальном проекте Task Manager.
https://github.com/NikGor/TaskManager

беру issue в работу

**Comment by fey** [comment]
Вообще тут надо скорректировать логику, по которой будут подсвечиваться лейблы. 
Если не выбран ни один лейбл - то все серого цвета.
Если выбран лейбл по которому фильтрация - то только он подсвечивается. 
Если нажимаем на следующий лейбл, то он добавляется и посвечивается тоже. 

Также есть баг щас с тем, что допустим выбрали один из лейблов https://friends.hexlet.io/issues/?contribution_labels=enhancement
То будут подсвечены все лейблы, которые есть у ищщусов (даже тот лейбл, который мы не выбирали для фильтрации). 

Короче говоря лейбл горит синим, если по нему фильтруем


![image](https://github.com/Hexlet/hexlet-friends/assets/697178/13e238f1-a42d-4780-a22b-461518024968)

**Comment by NikGor** [comment]
> @NikGor можете показать, как это выглядит? Потыкал проект, не увидел https://python-project-52-production.up.railway.app/tasks/

да, я оставил 4-й проект как есть, и таск-менеджер у меня как сайд-проект: https://github.com/NikGor/TaskManager
Но у меня это поведение все-таки сделано через JS

**Comment by NikGor** [comment]
> Вообще тут надо скорректировать логику, по которой будут подсвечиваться лейблы. Если не выбран ни один лейбл - то все серого цвета. Если выбран лейбл по которому фильтрация - то только он подсвечивается. Если нажимаем на следующий лейбл, то он добавляется и посвечивается тоже.
> 
> Также есть баг щас с тем, что допустим выбрали один из лейблов https://friends.hexlet.io/issues/?contribution_labels=enhancement То будут подсвечены все лейблы, которые есть у ищщусов (даже тот лейбл, который мы не выбирали для фильтрации).
> 
> Короче говоря лейбл горит синим, если по нему фильтруем
> 
> ![image](https://user-images.githubusercontent.com/697178/262618781-13e238f1-a42d-4780-a22b-461518024968.png)

понял. Да, так и будет логично.
Еще вроде как не хватает кнопки ресета всех фильтров

**Comment by DREU007** [comment]
Беру в работу.

**Comment by DREU007** [comment]
@fey, Пофиксил отображение цветов. Вопрос по кнопке ресета. Сделать отдельно для всех фильтров или только для label?

**Comment by Shvidunov** [comment]
получилось наоборот - активные серым цветом выделяются. Может есть смысл наоборот сделать? Неактивные серые (как то логичнее), активные синие. Но тогда при переходе на страницу все фильтры должны быть отключены (серый цвет).

**Comment by fey** [comment]
давайте активные зеленым сделаем, а неактивные - серым. 
Посмотрите какие есть классы в бутстрапе. По-моему для зеленого можно success класс использовать, а для серого - secondary или outline если это возможно.

**Comment by fey** [comment]
@DREU007 обычно на форме есть кнопка-ресета для всей формы.

**Comment by DREU007** [comment]
[Задеплоил](https://hexlet-friends-vkia.onrender.com/issues/)
[GitHub](https://github.com/DREU007/hexlet-friends/tree/issue_294_fix_filter_color)
