### ISSUE TITLE
Смещение записей в таблице Pull requests из-за нумерации

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#295]
## Ожидаемое поведение

Ровные колонки в таблице раздела Pull requests

## Текущее поведение

Смещение записей в таблице при появлении 2-х и 3-х значных порядковых номеров записей.

![image](https://github.com/Hexlet/hexlet-friends/assets/121935818/3334852f-308c-4d7c-96a7-f7974b57915a)

## Дейсвия по воспроизведению

1. Перейти на страницу Pull requests
2. пролистать до порядкового номера 10, 100

## Информация об установленных зависимостях

    pip freeze

**Comment by dmitriy-ga** [comment]
Беру в работу
