### ISSUE TITLE
В списке для сравнения вклада участников отсутствует сортировка по алфавиту

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#298]
## Ожидаемое поведение

При просмотре списка в для сравнения вклада ожидается сортировка этого списка в алфавитном порядке

## Текущее поведение

В списке нет сортировки по алфавиту, принцип сортировки неочевиден
![image](https://github.com/Hexlet/hexlet-friends/assets/121935818/da9e3845-adf4-40f5-af0e-5a86d39a726c)

## Возможные решения

добавить сортировку в алфавитном порядке по умолчанию для удобства пользования

## Действия по воспроизведению

1. Авторизоваться, нажать на имя пользователя, выбрать вариант "моя статистика" 
2. На странице статистики в разделе "вклад за все время" нажать на поле "сравнить с ..."
3. Проверить появившийся список участников для сравнения

## Информация о вашей системе

выбирать участника для сравнения неудобно 

win10 home, chrome

## Информация об установленных зависимостях

    pip freeze

**Comment by NikGor** [comment]
I'll take this issue. Please note that this is my first issue in open-source projects after taking a course on Hexlet

**Comment by Dzigr** [comment]
@NikGor Привет, глянь этот [issue](https://github.com/Hexlet/hexlet-friends/issues/310), так как он немного заменяет текущий. Если готов - можем взяться вместе.

**Comment by NikGor** [comment]
issue вроде как неактуально и перекрывается другим issue, но список по алфавиту отсортировал.
В отсортированном списке стала видна новая проблема - множество значений None
