### ISSUE TITLE
Добавить возможность набора текста в выборе из списка для сравнения вклада участников

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#300]
## Предлагаемая задача

Сейчас выбор из списка участников для сравнения вклада реализован только с помощью скроллинга. Для удобства поиска конкретного участника можно добавить поиск по набору текста.

## Решения задачи

добавить к выпадающему списку участников возможность поиска по набору текста

**Comment by fey** [comment]
Неактуально, тк это будем удалять в #390
