### ISSUE TITLE
Открывать ссылку на GitHub в профиле участника в новом окне

### ISSUE THREAD

**Issue by gayaleeva** [Hexlet/hexlet-friends#302]
## Предлагаемая задача
Ссылки на GitHub в профиле участников открываются в текущей странице

## Решения задачи
Думаю, ссылки на внешний ресурс лучше открывать на новой странице

**Comment by EmilMorua** [comment]
Беру в работу!

**Comment by EmilMorua** [comment]
Добавил тэги для открытия ссылок на GitHub в новом окне в профиле участника
