### ISSUE TITLE
Использовать логины участников вместо имен в списке для сравнения вклада участников

### ISSUE THREAD

**Issue by gayaleeva** [Hexlet/hexlet-friends#303]
## Предлагаемая задача
Лучше использовать логины участников вместо имён в выпадающем списке для сравнения вклада, т.к. у некоторых участников не заполнено имя:

![список](https://i.ibb.co/b31nwdf/2121-1.png)

## Решения задачи
Использовать логины участников вместо имён в выпадающем списке для сравнения вклада

**Comment by fey** [comment]
Пока этот ищщус на паузу. Рассмотрим другой интерфейс для сравнения участников
