### ISSUE TITLE
Поменять инструкцию по деплою. заменить railway на render com

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#306]
## Предлагаемая задача
Railway закрыл бесплатные тарифы. Переходим на render для деплоя демок. 

## Решения задачи
Обновить инструкцию, поменять railway на render

**Comment by yudzhum** [comment]
беру в работу

**Comment by fey** [comment]
@yudzhum Юлия, в ПРе https://github.com/Hexlet/hexlet-friends/pull/320 обновили инструкцию.
Можете по ней пройтись и проверить, ок не ок? Если все ок, то ищщус закрываем.

**Comment by yudzhum** [comment]
Проверила, все ок
