### ISSUE TITLE
Подключить Sentry для мониторинга и трекинга ошибок

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#307]
## Предлагаемая задача

Сейчас нет информации о том, что происходит с продом. Например получаем 500 ошибку, но нет инфы, что да как. Раньше для трекинга ошибок использовали rollbar, сейчас будем использовать Sentry, тк он получше по лимитам + можно самим его захостить.

## Решения задачи

Подключить sentry в проект, в пулл реквесте показать инструкцию по подключению (по сути это должно быть добавление токена и все). Сделать деплой демки и показать скрины из дашборда сентри, где будут эти ошибки видны.

**Comment by Dzigr** [comment]
Возьмусь
