### ISSUE TITLE
Реализовать страницу сравнения статистики

### ISSUE THREAD

**Issue by Dzigr** [Hexlet/hexlet-friends#310]
## Предлагаемая задача
Заменить текущее сравнение вклада участников, сделав отдельную страницу с таблицей сравнения.

## Решения задачи
1. Убрать форму "сравнить с" из личного профиля.

![image](https://github.com/Hexlet/hexlet-friends/assets/109955706/bf48ec12-f304-465e-a7c5-0573c5ec1887)

2. При просмотре профиля другого пользователя изменить работу кнопки сравнения статистики.

![image](https://github.com/Hexlet/hexlet-friends/assets/109955706/aeeb52bf-d862-460e-8d22-163ab1bec571)

3. Добавить отдельную страницу вывода сравнения статистики в виде таблицы (как пример - Steam).

Связанные и приостановленные issues:
[298](https://github.com/Hexlet/hexlet-friends/issues/298)
[300](https://github.com/Hexlet/hexlet-friends/issues/300)
[303](https://github.com/Hexlet/hexlet-friends/issues/303)

**Comment by NikGor** [comment]
@Dzigr привет, я issue по алфавитной сортировке участников все равно исправил.
Можем взяться вместе конечно

**Comment by Dzigr** [comment]
@NikGor привет. Как будет время пиши тогда в [telegram](https://t.me/dmitrybrag)

**Comment by DmGorokhov** [comment]
@Dzigr Привет! Готов вместе поработать над задачей!

**Comment by DmGorokhov** [comment]
я пока на этапе развернтывания проекта локально, там появились нюансы по докеру, отпишусь в ММ для обсуждения. Т.е. пока в конекст задачи еще не зашел

**Comment by DmGorokhov** [comment]
привет! давайте я пока освобожу задачу, тк никак до нее не дойду и на этой неделе это тоже маловероятно. Если никто не возьмет, то вернусь уже по готовности

**Comment by fey** [comment]
Отлично, если что - пишите.

**Comment by NikGor** [comment]
Привет! Можно какие-то скрины " (как пример - Steam)." на что ориентироваться? По какому событию должен происходить переход на новую страницу? и т.д. Задание подробнее, если есть представление, что нужно получить

**Comment by NikGor** [comment]
> Смотрите, может быть отдельная страница, на которую мы попадаем по ссылке.
Ну хорошо, попробую поимпровизировать в своей ветке

**Comment by fey** [comment]
Да, тут пока ет четкого понимания и можно пофантазировать.
На мой взгляд подойдет отлично отдельная ветка. Вы можете посмотреть как в gitlab.com сравниваются изменения из двух коммитов/веток - там есть отдельная страница. Можно что-то в эту сторону пофантазировать)

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-friends/pull/380
