### ISSUE TITLE
Сделать Leaderboard

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#324]
Создаем раздел для рейтинга friends.hexlet.io/leaderboard 
там создаем несколько разделов, чтобы было удобно смотреть инфу
* по коммитам
* по ПРам
* по Ищщусам

Каждый раздел - это подстраница, типа `friends.hexlet.io/leaderboard/issues`

Плюсом добавляем сортировки и фильтры. Выводим пока топ 100 пользователей по каждым направлениям.

**Comment by asenka0301** [comment]
Здравствуйте, возьму в работу

**Comment by asenka0301** [comment]
возвращаю задачу, не мой стек, взяла по ошибке

**Comment by fey** [comment]
@asenka0301 а как у вас дела с версткой? Может хотите сверстать лендинг на бутстрапе?)

**Comment by asenka0301** [comment]
давайте, думаю справлюсь)

**Comment by NikolayZemelko** [comment]
Работаю над задачей

**Comment by fey** [comment]
@asenka0301 Анастасия, привет. Как у вас успехи? Продвинулись? Если нужна помощь, можете создать draft пулл реквест и например Николай присоединится к вам.

**Comment by asenka0301** [comment]
Привет) я не могу развернуть приложение с помощью docker, думаю связано с этим issue https://github.com/Hexlet/hexlet-friends/issues/328. Вижу пулреквест с правками https://github.com/Hexlet/hexlet-friends/pull/337, когда его смержат надеюсь проблема решится.

**Comment by fey** [comment]
Теперь следующий этап - нужно нужно лендинг разделить на части, перевести на шаблонизатор.

Для теста можно лендинг подключить на какую-нибудь отдельную страницу например friends.hexlet.io/landing, чтомы мы могли вносить изменения и когда все будет готово - заменить главную страницу.
