### ISSUE TITLE
Bug: Не работает инструкция локального развертывание на новом движке Docker Compose (V2) 

### ISSUE THREAD

**Issue by DmGorokhov** [Hexlet/hexlet-friends#328]
[Compose](https://docs.docker.com/compose/) с июля 2023 года больше не поддерживает версию V1 движка. Версия V2-теперь это CLI надстройка к докеру. Меняется семантика команд compose: docker-compose -> docker compose. Для новых участиков проекта команды инструкции по установке и команды make в части docker могут не работать, если уже новый движок поставили.

1. Надо внести правки в Makefile в команды по docker compose.
2. Надо внести правки\комментарии в инструкцию по установке в части docker compose.
3. В инструкции по установке можно заменить команду `source $HOME/.cache/pypoetry/virtualenvs/<name of the created environment>/bin/activate` на `poetry shell`.
4. В файле docker-compose.yaml указаны ссылка на dockerfile.dev, а по факту Dockerfile.dev. Сборка падает с ошибкой.
5. У меня движок compose V2 и инструкция  `RUN poetry install --extras psycopg2-binary` в  Dockerfile.dev падает с ошибкой.
![Docker-install failed  from 2023-08-26 19-25-07](https://github.com/Hexlet/hexlet-friends/assets/117211516/cbf47146-19ec-4e02-b995-33ac6d3b7530)
Это связно в первую очередь с особенностями образов по тэгам 'alpine' именно для Python. 
[Здесь](https://pythonspeed.com/articles/alpine-docker-python/) и [здесь](https://pythonspeed.com/articles/base-image-python-docker-images/) описана проблематика.

Поэтому предлагаю:

6. Перейти на базовый образ python по тэгу 'slim'- пока для локального окружения. Это позволит: уменьшить количество слоев образа, уменьшить время сборки, позволит исключить ошибки установки psycopg2-binary. Цена за это- увеличение размера  образа(~400Мб). Размер можно уменьшить при желании, прописав удаление ненужных предустановленных библиотек.

8. Опционально: для контейнера экспортировать зависимости из poetry в requremets.txt и в контейнере ставить через pip, не устанавливая poetry. Это уменьшит время сборки и избавит от установки лишней библиотеки в контейнере. Можно для локальных сборок обкатать. 

**P.S. Готов все пункты сделать.**

**Comment by fey** [comment]
Да, давайте. Присылайте ПР. надо переходить на v2 версию, поэтому можно убирать тире.

**Comment by DmGorokhov** [comment]
Ок, подготовлю!
