### ISSUE TITLE
Bug: Раздел "Нерешенные проблемы", ошибка 500 при выборе опции 'good first issue'

### ISSUE THREAD

**Issue by yudzhum** [Hexlet/hexlet-friends#330]
## Ожидаемое поведение

Загрузка страницы и вывод результатов поиска

## Текущее поведение
При поиске по разделу "нерешенные проблемы" с выбранной опцией 'good first issue' получаем Server Error (500)

## Действия по воспроизведению

1. На главной странице перейти в раздел "Нерешенные проблемы"
2. Отметить чекбокс 'good first issue'
3. Нажать на кнопку "поиск"
4. Получаем Server Error (500)

## Информация о вашей системе

Система: Win 11
Браузер: Chrome

## Информация об установленных зависимостях

    pip freeze

**Comment by ajib6ept** [comment]
Беру в работу

**Comment by ajib6ept** [comment]
Исправлено, pull request #331
