### ISSUE TITLE
Bug: HTTPError 401 Client Error: Unauthorized for url: https://api.github.com/orgs/hexlet-components/installation

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#332]
Пришла ошибка из sentry https://nikolay-gagarinov.sentry.io/share/issue/a7df4493c2974ac285d371489c827752/

**Comment by Abdujabbar** [comment]
@fey  Тут тоже ссылка мертвая, можешь глянуть и поделиться с рабочей ссылкой? 

Спасибо

**Comment by fey** [comment]
К сожалению нет(
