### ISSUE TITLE
Bug:  разделе "Нерешенные проблемы" не работает пагинация

### ISSUE THREAD

**Issue by ajib6ept** [Hexlet/hexlet-friends#338]
## Ожидаемое поведение
Ссылки на страницы если отображаются, то должны возвращать результат

## Текущее поведение
Возвращается 404-ошибка

## Дейсвия по воспроизведению

1. На главной странице перейти в раздел "Нерешенные проблемы"
2. Имя репозитория указать 'hexlet-friends'
3. Нажать на кнопку "поиск"
4. Выбираем страницу "2" или "3" или "4" или "5"

![image](https://github.com/Hexlet/hexlet-friends/assets/5192447/73c611d0-c58b-4d70-8dde-c344fc0882ec)

## Информация об установленных зависимостях

    pip freeze

**Comment by NikGor** [comment]
Беру в работу

**Comment by fey** [comment]
@DREU007 можете взять в работу =)

**Comment by fey** [comment]
@SvetlanaAkaemova возьмете в работу? =)

**Comment by StanislavSol** [comment]
Можно взять в работу?

**Comment by fey** [comment]
@StanislavSol Да, берите.

**Comment by StanislavSol** [comment]
@fey Спасибо. Взял.

**Comment by StanislavSol** [comment]
А сюда можно писать вопросы?

**Comment by fey** [comment]
да, можно. Но на прям технические вряд ли смогу ответить.

**Comment by HelenOne** [comment]
@StanislavSol как дела с задачкой?

**Comment by StanislavSol** [comment]
@HelenOne Пока плохо, нет никакой коммуникации, что бы разобраться. В комьюнити и интершип мои вопросы были проигнорированы. Но я всё хочу выполнить эту задачку.

**Comment by HelenOne** [comment]
@StanislavSol поняла, сейчас попробую активизировать помощь повторно

Еще вижу вы взяли несколько задачек в работу, может готовы поделиться какой-нибудь с другими желающими? Либо поработать над одной из задач совместно?

**Comment by StanislavSol** [comment]
По тем задачкам я отправил пулреквесты в начале недели. Никто их не проверяет. Осталась только эта задачка. Как выглядит совместная работа? Как будет приниматься пулреквест?

**Comment by StanislavSol** [comment]
@HelenOne По тем задачкам я отправил пулреквесты в начале недели. Никто их не проверяет. Осталась только эта задачка. Как выглядит совместная работа? Как будет приниматься пулреквест?

**Comment by HelenOne** [comment]
@StanislavSol 
По пулреквестам сейчас попросила проверить, пока ждем
По поводу совместной работы - можно в формате парнокодинга, либо если задача обширная разделить задачу и коммитить параллельно в один пулреквест
В формате совместной работы иногда быстрее получается разобраться с возникающими проблемами, не ожидая помощи наставников

**Comment by StanislavSol** [comment]
ок, давайте, если потенциальный партнер согласен.

**Comment by StanislavSol** [comment]
Проблему решил https://github.com/Hexlet/hexlet-friends/pull/386
