### ISSUE TITLE
Bug: Во вкладке issue нет переноса длинных названий issue, появляется горизотнальный скролл

### ISSUE THREAD

**Issue by DmGorokhov** [Hexlet/hexlet-friends#342]
Необходимо поставить ограничение на длину столбца с названием issue и делать перенос при длинном названии.

![image](https://github.com/Hexlet/hexlet-friends/assets/117211516/632ecb8e-ea05-4ff8-915b-ab24aee4b17a)
![image](https://github.com/Hexlet/hexlet-friends/assets/117211516/6f47861b-e475-4cf0-8cd3-6c9c71900cb7)

**Comment by u-shev** [comment]
Взяла в работу
