### ISSUE TITLE
Сделать тесты (Leaderboard)

### ISSUE THREAD

**Issue by NikolayZemelko** [Hexlet/hexlet-friends#347]
Реализован функционал Leaderboard, необходимо добавить тесты на этот функционал. 

https://github.com/Hexlet/hexlet-friends/labels/feature%20request
https://github.com/Hexlet/hexlet-friends/labels/backend
https://github.com/Hexlet/hexlet-friends/labels/help%20wanted

**Comment by ajib6ept** [comment]
беру в работу
