### ISSUE TITLE
Bug: Акутализировать инструкцию по установке

### ISSUE THREAD

**Issue by DmGorokhov** [Hexlet/hexlet-friends#348]
1.) В п 1.2 инструкции написать про необходимость установить переменную DEBUG= True при разработке. Иначе по умолчанию идет редирект по протоколу HTTPS вместо HTTP. HTTPS не поддерживается development сервером.
2.) Попроваить команду compose-dev на команду compose-start, которая по факту прописана в Makefile

**Comment by u-shev** [comment]
Возьму

**Comment by fey** [comment]
@DmGorokhov проверьте, пофикшено. Если ок - закрывайте.

**Comment by DmGorokhov** [comment]
Да, все ок. @u-shev Спасибо!
