### ISSUE TITLE
Bug: Ошибка при наполнении базы данных

### ISSUE THREAD

**Issue by TarakanovAndrey** [Hexlet/hexlet-friends#359]
## Ожидаемое поведение

Загрузка данных по репозиториям "Hexlet"
## Текущее поведение

Возникает исключение:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/Hexlet/hexlet-cv/pulls/54/merge
```
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/pulls/pulls#check-if-a-pull-request-has-been-merged"
}
```
Загрузка данных прекращается.
При отдельной загрузке конкретно из 'hexlet-cv' исключение не возникает:
```
make sync ARGS='--repo Hexlet/hexlet-cv'
```
## Дейсвия по воспроизведению

1. ```make sync ARGS='Hexlet'```

## Информация о вашей системе

Ubuntu, Pycharm

## Информация об установленных зависимостях

    pip freeze

**Comment by TarakanovAndrey** [comment]
Дополнение: наполнение данных обваливается на разных стадиях. Причина как я понял на стороне гитхаба, обрывают соединение. Все репозитории Хекслета мне не удалось подгрузить на локальную машину

**Comment by DmGorokhov** [comment]
Тут не исключено, что гитхаб обрывает соединение, тк при запросе по Hexlet идет закачка данных по всем репозиториям- много трафика с одного запроса. У вас около 37 репозиториев скачивается и обрывается, примерно так?

**Comment by TarakanovAndrey** [comment]
[DmGorokhov](https://github.com/DmGorokhov) Да, примерно на этом количестве обрывается

**Comment by DmGorokhov** [comment]
Разобрался. У апи гитхаба [лимит](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) 5000 запросов в час и при загрузке по большой оранизации (Hexlet например) мы его превышаем (на скрине ниже вывел в консоль счетчик лимита).
В инструкции дан неудачный пример команды, тк все кто приходят на проект- идут по шагам, копируют команды и натыкаются на эту ошибку. Хотя даже с этой ошибкой локальная база становится более чем наполненной)))
Я тогда поправлю пример (организацию поменьше поставлю) в инструкции и напишу комментарий. Для разработки в принципе выкачивать столько не нужно. Можно конретных репозиториев покачать.
![image](https://github.com/Hexlet/hexlet-friends/assets/117211516/d12dc2da-ad5a-40c6-a362-962ba6bf895e)
