### ISSUE TITLE
Добавить canonical url для параметрических страниц

### ISSUE THREAD

**Issue by usernaimandrey** [Hexlet/hexlet-friends#364]
## Предлагаемая задача
Нужно на параметрических страницах настроить тег canonical где указать соответствующий урл, но без параметров
Пример:
https://friends.hexlet.io/?utm_source=hexlet&utm_medium=blog&utm_campaign=hexlet&utm_content=itogi-2022-goda&utm_term=post_301222 -> соответственно canonical url **https://friends.hexlet.io**

https://friends.hexlet.io/contributors/?page=59&sort=-name -> canonical: **https://friends.hexlet.io/contributors**

https://friends.hexlet.io/repositories/?search=nodos&sort=-issues&labels=html.elixir.clojure -> **https://friends.hexlet.io/repositories**

Для чего это нужно: Что бы параметрические страницы не попадали в индекс поисковых систем

## Решения задачи

Добавить canonical url

**Comment by jespy666** [comment]
Попробую взять в работу
