### ISSUE TITLE
Обработчик для лендинга

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#372]
Теперь следующий этап - нужно нужно лендинг разделить на части, перевести на шаблонизатор.

Для теста можно лендинг подключить на какую-нибудь отдельную страницу например friends.hexlet.io/landing, чтомы мы могли вносить изменения и когда все будет готово - заменить главную страницу.

https://github.com/Hexlet/hexlet-friends/blob/main/templates/landing.html

**Comment by DREU007** [comment]
Беру в работу

**Comment by fey** [comment]
@DREU007 Как успехи? Нужна помощь?

**Comment by DREU007** [comment]
@fey, пока остановился, занят другими делами. Постараюсь на днях разобрать.

**Comment by fey** [comment]
Окей, если что пишите. Если вдруг прям не получается взяться за задачку - можно ее оставить другим ребятам. Будут другие задачи =)

**Comment by al-ov73** [comment]
@fey   Задача открыта? Могу взять?

**Comment by DREU007** [comment]
@al-ov73, продолжи [с уже сделанным мной](https://github.com/DREU007/hexlet-friends/tree/feat_new_landing)
@fey, Освобожу задачу

**Comment by fey** [comment]
Вообще есть пулл реквест) https://github.com/Hexlet/hexlet-friends/pull/378
уже 
Я предлагаю @al-ov73 развернуть локально, посмотреть все ли хорошо, можете код поревьювить, задать вопрсосы, если что-то непонятно. 
Скорее всего этот ПР мы смержим и будем двигаться дальше.

**Comment by al-ov73** [comment]
> Вообще есть пулл реквест) #378 уже Я предлагаю @al-ov73 развернуть локально, посмотреть все ли хорошо, можете код поревьювить, задать вопрсосы, если что-то непонятно. Скорее всего этот ПР мы смержим и будем двигаться дальше.

Хорошо, я локально развернул ветку с лендингом, посмотрю.
Выберу тогда какой-нибудь другой PR
