### ISSUE TITLE
Актуализировать инструкцию по деплою на Render

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#381]
Сейчас в статье есть неточности, которые нужно поправить.

Например раздел про работу с переменными. Указано, что нужно записывать их в `.env`, но по факту лучше их прописать как переменные. Плюс не все переменные перечислены. Часть из них есть в доке по разворачиванию локально.

![image](https://github.com/Hexlet/hexlet-friends/assets/697178/15698714-5f75-4d35-a355-7a058ba369d8)

**Comment by fey** [comment]
Плюсом почемуто миграцию нам нужно выполнять локально, хотя ее можно автоматизировать, добавив в `build-production` нужную команду (надо потестить).

**Comment by StanislavSol** [comment]
Беру!

**Comment by StanislavSol** [comment]
https://github.com/Hexlet/hexlet-friends/pull/384
