### ISSUE TITLE
Улучшить команды деплоя и предврительной настройки приложения для разработки

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#382]
Сейчас команда настройки проекта локально состоит из нескольких сложных этапов.
Что можно сделать

1) Главную команду оставить make setup, она включает себя все необходимые шаги, в тч make install
2) для подготовки виртуальногоокружения можно использовать `poetry shell`
3) в `.env` файле сразу прописывать необходимые переменные окружения
4) создавать суперпользователя с заданным паролем (вероятно добавить еще одну команду), чтобы мыло команду сетапа запускать без прерывания на интерактив

**Comment by StanislavSol** [comment]
Беру!

**Comment by StanislavSol** [comment]
https://github.com/Hexlet/hexlet-friends/pull/385
