### ISSUE TITLE
Bug: Неправильно отрабатывает пагинация

### ISSUE THREAD

**Issue by amahmetov1998** [Hexlet/hexlet-friends#387]
## Действия по воспроизведению
1. Зайти в раздел "Проблемы"
2. Ввести в любое поле строку, выводящую результат в виде 8 страниц (я ввел в поле 'имя репозитория' символ 'f')

## Текущее поведение
Неправильно работает пагинация (причем баг появляется только если результат представлен 8-ю страницами, в остальных случаях выводит нормально)

<img width="636" alt="image" src="https://github.com/Hexlet/hexlet-friends/assets/113240113/7ad04e17-b8b5-4089-8a7b-e7549d20d014">
<img width="606" alt="image" src="https://github.com/Hexlet/hexlet-friends/assets/113240113/42be399b-95a0-4421-86a7-cf9103ae0106">

**Comment by IlyaBag** [comment]
Беру задачу

**Comment by amahmetov1998** [comment]
@IlyaBag Привет, я уже ее решил, осталось ПР сделать

**Comment by IlyaBag** [comment]
Хорошо)
