### ISSUE TITLE
Удалить "Сравнить с..." с выбором юзера

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#390]
В задаче https://github.com/Hexlet/hexlet-friends/issues/310 сделали кнопку для сравнения с юзером у которого мы находимся профиле.

Соответственно старое нам больше не нужно. 

![image](https://github.com/Hexlet/hexlet-friends/assets/697178/bb61c13f-a18b-419a-916e-4b1f0bf24a5b)

**Comment by Belekov-Aden** [comment]
Добрый день! Беру первый свой issue.

**Comment by fey** [comment]
@Belekov-Aden Привет как успехи? Если что задачку пока раздаю ребятам. Если успеете - присылайте ПР.

**Comment by fey** [comment]
А блин, мы ж это пофиксили. https://github.com/Hexlet/hexlet-friends/pull/396
