### ISSUE TITLE
Bug: Инструкция по развертыванию на Render некорректна

### ISSUE THREAD

**Issue by prStudentka** [Hexlet/hexlet-friends#398]
## Ожидаемое поведение
следуя заявленным шагам инструкции, произошел успешный деплой на Render

## Текущее поведение
Деплой проходит, но не хватает статик файлов. https://hexlet-friends-ezn7.onrender.com 

В инструкции шаг 3. Создание веб-приложения.
Результат: в Render отсутствуют поля Runtime, Build Command, Start Command.
###### Описание проблемы:
Render видит Docker в репозитории и сам создает сервис с Docker, а в инструкции это не учитывается.
Таким образом, шаг не возможно выполнить в полной мере.

**Comment by prStudentka** [comment]
> @prStudentka можете дополнить инструкцию и прислать пулл реквест с исправлением?

Правильный пулл реквест или что-то исправить?

**Comment by fey** [comment]
@prStudentka ждем ревью от @sgmdlt

**Comment by sgmdlt** [comment]
> В инструкции шаг 3. Создание веб-приложения.
> Результат: в Render отсутствуют поля Runtime, Build Command, Start Command.

> Описание проблемы:
> Render видит Docker в репозитории и сам создает сервис с Docker, а в инструкции это не учитывается.
> Таким образом, шаг не возможно выполнить в полной мере.

Добрый день, а вы указывали как в инструкции Runtime: Python 3 ?
Я сейчас повторил все шаги из инструкции, и деплой работает.

**Comment by prStudentka** [comment]
@sgmdlt  О! Точно. Runtime у меня Docker. 
Так, что дальше делать? Что-то закрыть, откатить?

**Comment by sgmdlt** [comment]
Подождите, скажите что вы пытаетесь решить пул реквестом?

Я попробовал повторить развертывание по инструкции, и все получилось. Никаких ошибок как у вас в ишьюсе не было.

**Comment by prStudentka** [comment]
@sgmdlt Инструкция соответствует, хорошо. Я учусь и пытаюсь узнать, какие сейчас нужны от меня шаги дальше?

**Comment by sgmdlt** [comment]
Если нет никакого ишьюса, то никаких действий и не нужно) Я просто закрою ПР.

**Comment by prStudentka** [comment]
@sgmdlt ОК. А пулл реквест еще висит, он тоже закроется?

**Comment by sgmdlt** [comment]
Да, я закрою тот ПР и ишьюс. А вообще у вас получилось задеплоить по инструкции?

**Comment by prStudentka** [comment]
@sgmdlt Понятно. Спасибо, что объяснили. Да. Получилось задеплоить по инструкции. https://hexlet-friends-1.onrender.com/
