### ISSUE TITLE
remove WPS, use flake8

### ISSUE THREAD

**Issue by AleksandrKosmylev** [Hexlet/hexlet-friends#443]
## Ожидаемый результат
Отсутствие комментариев # noqa: WPS в  проекте.

## Текущий экземпляр закомментированной строки
https://github.com/Hexlet/hexlet-friends/blob/58300b2ea1342dc638d9c0fe9f05e494233ba6d5/contributors/views/mixins.py#L7

**Comment by kat-git-hub** [comment]
возьму в работу

**Comment by fey** [comment]
Let's get away from WPS completely. In Hexlet we use flake8

**Comment by kat-git-hub** [comment]
Removed 'wemake-python-styleguide' from pyproject.toml and changed configuration in setup.cfg

**Comment by kat-git-hub** [comment]
update poetry.lock

**Comment by kat-git-hub** [comment]
обновила зависимости - добавила flake8

**Comment by fey** [comment]
fixed?

**Comment by kat-git-hub** [comment]
yep, merged and closed
