### ISSUE TITLE
Bug: Language switch not working

### ISSUE THREAD

**Issue by NikGor** [Hexlet/hexlet-friends#476]
### Summary

403 Error: CSRF verification failed. Request was rejected.

### Reproduction steps

```bash
Go to the website
Try to change the language using the language switcher in the top-right corner.
```

### Expected result

The language should change after selecting a different language from the dropdown menu.

### Actual result

 When attempting to change the language (e.g., from Russian to English), the action fails, and a 403 CSRF verification error is displayed

### Browsers

Chrome

### OS

Linux

**Comment by remortalite** [comment]
Looks like #475 and #476 are both from page caching. After 15 minutes cache updates and the page loads new data with username and correct csrf token
