### ISSUE TITLE
Спрятать кнопки входа/регистрации на публичных страницах

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#60]
Я как пользователь хочу заходить на сайт через гитхаб, чтобы не тратить время на создание аккаунта.

**Comment by astynax** [comment]
Можно. Но п о сути в этот проект не нужно "заходить". Сейчас пользователь вообще один, и тот - админ. Нужен он для того, чтобы настроить организации и репозитории.

**Comment by fey** [comment]
Может тогда кнопки логина и регистрации спрятать пока? Чтобы не вводить в заблуждение

**Comment by astynax** [comment]
Спрячьте. Пусть только в админке останется форма логина.
