### ISSUE TITLE
Добавить ТОПы пользователей (leadboard)

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#73]
ТОП 5(10) самых активных пользователей за неделю, месяц.
Можно вывести такой топ на главной странице.

**Comment by antlu** [comment]
Это на замену таблице на главной странице?
Потому что эти "топы" сейчас можно получить сортировкой по столбцам.

**Comment by astynax** [comment]
Можно сделать умолчательную сортировку. Или скорее просто сделать упрощённое представление: "Топ 10 коммиттеров" без столбцов и сортировок с возможностью перейти к подробной таблице.
