### ISSUE TITLE
Вывести на главную 5-10 последних коммитов/пулреквестов

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#74]

**Comment by antlu** [comment]
А какая польза от этого?

**Comment by astynax** [comment]
Это "индикатор движухи" эдакий.

**Comment by leksuss** [comment]
Можно мне назначить? 

И где на главной это лучше выводить - внизу под "недавно активными" или, может, разбить на две колонки?

**Comment by antlu** [comment]
Ожидается, что таблица на главной странице заменится на список имён. Поэтому можно не организовывать колонки с ней.
Вместо коммитов лучше issues выводить.

**Comment by leksuss** [comment]
Что-то типа такого, например?
<img width="448" alt="Снимок экрана 2020-04-16 в 12 55 11" src="https://user-images.githubusercontent.com/11560975/79442660-8725ec00-7fe1-11ea-9705-d398376c1a35.png">
