### ISSUE TITLE
Аккумулировать issues со всех проектов

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#75]
Вывести список задач со всех проектов, чтобы пользователь мог легко выбрать себе задачу - https://hexlet-friends-antlu.herokuapp.com/issues/

**Comment by altvec** [comment]
А разве это уже не сделано в #61 ?

**Comment by AABur** [comment]
Повторю вопрос - вроде уже реализовано и работает. Может стоит закрыть этот issue?

**Comment by astynax** [comment]
Да, можно закрывать.
