### ISSUE TITLE
Разработать стандарт описания проектов

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#76]
Из описания должно быть понятно, как можно начать и влиться в проект (и вообще в опенсорс Хеслета).

**Comment by acidmaksim** [comment]
@zhabinka это не оно - https://guides.hexlet.io/ru/how-to-be-a-helpful-for-the-hexlet-community/ ?

**Comment by zhabinka** [comment]
Я предлагал это в ридми проекта добавить.

**Comment by zhabinka** [comment]
Я предлагал это в ридми проекта добавить.

**Comment by acidmaksim** [comment]
Сделать инструкцию по шагам, как в CodeBattle - https://github.com/hexlet-codebattle/battle_asserts/blob/master/CONTRIBUTING.md

**Comment by devdenh** [comment]
беру в работу

**Comment by devdenh** [comment]
https://github.com/Hexlet/hexlet-friends/pull/209
