### ISSUE TITLE
Добавить общий список всех проектов Хекслета

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#77]

**Comment by zhabinka** [comment]
Вывести описания, количество коммитов, звёзд и т.д.

**Comment by leksuss** [comment]
Дайте мне, пожалуйста, данный issue. Надо же с чего-то начинать )

**Comment by zhabinka** [comment]
Сейчас все проекты добавлены. Осталось codebattle добавить.

@astynax и работать над группировкой. Список репозиториев в нескольких кучках не очень удобно использовать.
