### ISSUE TITLE
Настроить регулярное обновление данных

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#79]

**Comment by antlu** [comment]
Это же задача для вас, команды Хекслета?

Если через планировщик делать, то в какой-нибудь Heroku Scheduler надо загнать выполнение `heroku run ./manage.py fetchdata`.

Если с вебхуками, то payload URL – `/event-handler`.
Я тестировал на этих событиях:
- Commit comments
- Issue comments 
- Pull request review comments
- Issues 
- Pull requests
- Pushes

**Comment by astynax** [comment]
ЕЯПП, `fetchdata` не особо разбирается в том, что нужно подтягивать? Там же просто всё сразу вытягивается - вся информация по каждому репозиторию? Мы уже упираемся в лимит по количеству запросов, так что "просто фетч всего по крону" не прокатит.

**Comment by antlu** [comment]
Превышение лимита запросов происходит только при начальном сборе данных.
Последующая синхронизация использует меньше запросов.

**Comment by astynax** [comment]
Хмм. Тогда попробую закронить, а на "горячие" репозитории поставлю вебхуки
