### ISSUE TITLE
Описание проекта

### ISSUE THREAD

**Issue by altvec** [Hexlet/hexlet-friends#8]
Может добавить описание проекта, дабы было понимание того, что мы делаем?

**Comment by astynax** [comment]
Так добавьте!

**Comment by altvec** [comment]
Если бы я знал :) Возможно тема обсуждалась в слаке, но я не нашел.

**Comment by astynax** [comment]
https://youtu.be/Cs8k9532SEM?t=1367 -- вот тут обсуждение, можно взять имфу для ридми

**Comment by altvec** [comment]
Сделал [pr](https://github.com/Hexlet/hexlet-friends/pull/13).

**Comment by altvec** [comment]
#13
