### ISSUE TITLE
Описать процесс установки приложения

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-friends#82]
Нужно подробное описание по установке и запуску, которое подойдёт и новичку в Django.
Разместить описание лучше в Wiki проекта.

**Comment by TurtleOld** [comment]
Привет, готов приступить, но есть вопрос.
В Makefile указан IP 0.0.0.0, но этот IP не добавлен в ALLOWED_HOSTS, соответственно мы получаем ошибку 500 при запуске  приложения.
Может быть изменить Makefile и указать 127.0.0.1 или добавить 0.0.0.0 в ALLOWED_HOSTS? 
А может ещё лучше - добавить аргумент к команде @poetry run python manage.py runserver 0.0.0.0:8000 [$(ARGS)]

**Comment by antlu** [comment]
Лучше открывать сайт по адресу localhost:8000 или 127.0.0.1:8000.

**Comment by TurtleOld** [comment]
> Лучше открывать сайт по адресу localhost:8000 или 127.0.0.1:8000.

В README файле фигурирует команда make start, которая запускает команду `@poetry run python manage.py runserver 0.0.0.0:8000`, но IP адрес 0.0.0.0 отсутствует в ALLOWED_HOSTS. В Wiki лучше тогда указать команду `poetry run python manage.py runserver localhost:8000` или 127.0.0.1:8000?

**Comment by antlu** [comment]
Можно оставить команду без изменений, но указать, что открывать нужно через localhost.

**Comment by TurtleOld** [comment]
> Можно оставить команду без изменений, но указать, что открывать нужно через localhost.

Хорошо, принял

**Comment by TurtleOld** [comment]
Я написал [wiki](https://github.com/TurtleOld/hexlet-friends/wiki/Install-and-run-application), но нельзя сделать PR на wiki страницу :)

**Comment by antlu** [comment]
@fey, настройками запрещено менять wiki.

**Comment by acidmaksim** [comment]
Закрывать задачу?
