### ISSUE TITLE
Группировка всех проектов Хекслета

### ISSUE THREAD

**Issue by leksuss** [Hexlet/hexlet-friends#88]
Я бы сгруппировал все это добро, если бы понимал что к чему относится :) 

На данный момент есть организации:
 - [hexlet-basics](https://github.com/hexlet-basics) с репозиториями-упражнениями под разные языки + ядро
 - [hexlet-codebattle](https://github.com/hexlet-codebattle) с основным репозиторием + для добавления новых задач и какие-то заброшенные
 - [hexlet-components](https://github.com/hexlet-components) - не в курсе что это
 - [hexlet-boilerplates](https://github.com/hexlet-boilerplates) - аналогично
 - [hexlet](https://github.com/hexlet) - основной, с кучей репозиториев для всего остального, в частности:
   - [hexlet-cv](https://github.com/hexlet/hexlet-cv)
   - [hexlet-sicp](https://github.com/hexlet/hexlet-sicp)
   - [hexlet-friends](https://github.com/hexlet/hexlet-friends)
   - [hexlet-interview](https://github.com/hexlet/hexlet-interview)
   - [hexlet-correction](https://github.com/hexlet/hexlet-correction)
   - [hexlet-editor](https://github.com/hexlet/hexlet-editor)

Итого есть code-basics, codebattle с одноименными организациями и перечисленные выше репозитории-проекты в организации hexlet. Все это можно назвать проектами.

Какие еще репозитории внутри организации hexlet можно выделить как проекты? Что можно выделить из других организаций как проекты?

**Comment by astynax** [comment]
Может лучше теги? С фильтрацией по тегам?

**Comment by leksuss** [comment]
Да, что-то типа тегов и получается. В целом я понял что надо сделать.

**Comment by leksuss** [comment]
А нужно ли вообще выделение такого понятия как "организации"? Участникам сообщества по большому счету неважно в какой организации находится проект или репозиторий. Идеологически есть проекты и репозитории относящиеся к тому или иному проекту. А то, что проекты находятся в разных организациях в рамках github - это технические моменты. Можно указать организацию там, где это важно для понимания, почему конкретно этот репозиторий находится по ссылке, например, github.com/hexlet-codebattle/codebattle, а не github.com/hexlet/codebattle

**Comment by leksuss** [comment]
И еще, надо бы заполнить базу проектов на проде.

**Comment by astynax** [comment]
Зполнить нужно, да
