### ISSUE TITLE
Учитывать комментарии\ревью\etc на гитхаб

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexlet-friends#9]
Предлагаю как вклад в проекты так же учитывать комментарии к коду\апрувы\реквесты\что там есть еще

Часть людей вносит свой вклад на гитхабе без пр-ов, давая столь полезные советы ;)

**Comment by Safintim** [comment]
Если все это можно вытащить, то было бы круто это добавить

**Comment by antlu** [comment]
Сделано в #16, #22.
