### ISSUE TITLE
В списке контрибьюторов есть лишние

### ISSUE THREAD

**Issue by antlu** [Hexlet/hexlet-friends#96]
1. ghost – изображает всех удалённых пользователей.
2. боты codecov, которые не идентифицируют себя ботами, иначе не были бы обработаны при сборе данных.
3. контрибьюторы [patterns](https://github.com/Hexlet/patterns/graphs/contributors), которые с Хекслетом не связаны.

Отключить их показ и обработку можно таким SQL-запросом:
```sql
UPDATE 
  contributors_contributor 
SET 
  is_tracked = FALSE, 
  is_visible = FALSE 
WHERE 
  login IN (
    'ghost', 'codecov-commenter', 'codecov-io'
  ) 
  OR login IN (
    SELECT 
      login 
    FROM 
      (
        SELECT 
          DISTINCT login, 
          contributor_id 
        FROM 
          contributors_contribution AS contributions 
          JOIN contributors_contributor AS contributors ON contributors.id = contributions.contributor_id 
        WHERE 
          contributions.repository_id = 122565211
      ) AS patterns_contributors 
      JOIN contributors_contribution AS contributions ON contributions.contributor_id = patterns_contributors.contributor_id 
    GROUP BY 
      login 
    HAVING 
      count(DISTINCT repository_id) = 1
  );
```
Только ryabtsovdm и it-amalker из этой выборки исключить надо.

**Comment by astynax** [comment]
Достаточно было в админке "выключить" по именам :)

**Comment by antlu** [comment]
Для троих можно и так, но в паттернах их 90.

**Comment by astynax** [comment]
Проще просто репу не трекать, чем таким вот майнингом заниматься
